apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: QA Test1
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env10
          artifact-id: 4380fe56-3d19-4e3e-8eeb-7b2bd0a9af1a
          target-environment: Approval
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env20
          artifact-id: ac12453b-c301-4917-90cf-72d8b561c811
          target-environment: TestQaEnv

