apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: QA Test1
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env10
          artifact-id: 4abec10c-58c6-4142-9f9a-545eb2e3876a
          target-environment: edge-env
