apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: QA Test1
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env10
          artifact-id: 9d3b7c30-b400-407b-9ad2-a0e76d5aa408
          target-environment: Approval
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env20
          artifact-id: 9d3b7c30-b400-407b-9ad2-a0e76d5aa408
          target-environment: TestQaEnv
